spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/hogehoge
    username: postgres
    password: postgres
    encoding: UTF-8
  jpa:
    database: POSTGRESQL
    hibernate: update